-- migrate:up

CREATE TABLE publication (
    id INT PRIMARY KEY,
    name VARCHAR(80) NOT NULL
);

CREATE TABLE atma (
    id INT PRIMARY KEY NOT NULL,
    lastname VARCHAR(80) NOT NULL
);

CREATE TABLE book(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(350),
    avg_rating FLOAT,
    format VARCHAR(50),
    image VARCHAR(50) UNIQUE,
    num_pages INTEGER,
    pub_date TIMESTAMP NOT NULL DEFAULT now(),
    pub_id INTEGER
);

CREATE INDEX book_title_index ON book(title);

ALTER TABLE book ADD CONSTRAINT fk_publication
FOREIGN KEY (pub_id)
REFERENCES publication(id);

-- migrate:down

