version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    networks:
      - default
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - database
